import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const newArticles = [
  {
    title: "OBD P0004 - Inyector Combustible Circuito B",
    keywords: ["p0004", "inyector", "combustible", "circuito b", "obd"],
    answer: "[SIGNIFICADO]\nCódigo de falla relacionado con el circuito de control del inyector de combustible en el cilindro B (banco 2).El sistema de control del motor ha detectado un problema en la señal de retroalimentación del inyector.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito abierto o en cortocircuito en el inyector de combustible. Bobina del inyector defectuosa. Conector o cableado dañado. Módulo de control del motor (ECU) con falla. Relé del inyector de combustible defectuoso.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del inyector desconectado o corrosionado\n- Cableado roto o dañado entre inyector y ECU\n- Inyector de combustible defectuoso o bloqueado\n- Resistencia incorrecta en el circuito del inyector\n- Falla en el relé de combustible\n- ECU defectuosa\n- Alimentación eléctrica intermitente al inyector\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Conectar escáner OBD para confirmar el código P0004\n2. Inspeccionar visualmente el conector y el cableado del inyector\n3. Verificar la continuidad del cableado con multímetro\n4. Medir la resistencia del inyector (debe estar entre 6-15 ohmios típicamente)\n5. Probar la inductancia del inyector\n6. Verificar la alimentación en el inyector durante el arranque\n7. Reemplazar el inyector defectuoso si es necesario\n8. Verificar la conexión del relé de combustible\n9. Borrrar el código de falla y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0006 - Inyector Combustible Circuito C Bajo",
    keywords: ["p0006", "inyector", "combustible", "circuito c", "bajo", "obd"],
    answer: "[SIGNIFICADO]\nEl sistema ha detectado un voltaje bajo o ausente en el circuito de control del inyector de combustible C (cilindro 3 banco 2). Indica problemas en la entrega de señal de pulso al inyector.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito abierto en el inyector. Bobina del inyector dañada. Conector suelto o corrosionado. Cableado fracturado. Falla en el transistor de conmutación de la ECU. Batería descargada.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del inyector C desconectado o con mal contacto\n- Cableado abierto o con alta resistencia\n- Inyector defectuoso con bobina abierta\n- Corrosión en los contactos del conector\n- Falla en la etapa de conducción de la ECU\n- Voltaje de batería bajo\n- Terminal desconectado en la batería\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar el estado de carga de la batería\n2. Revisar el conector del inyector C para corrosión\n3. Limpiar los contactos del conector\n4. Probar la continuidad del cableado entre inyector y ECU\n5. Medir la resistencia del inyector\n6. Hacer prueba de caída de voltaje en el circuito\n7. Sospechar de falla interna de la ECU si todo lo demás está bien\n8. Reemplazar el inyector si está defectuoso\n9. Reprogramar la ECU si es necesario\n[/SOLUCION]"
  },
  {
    title: "OBD P0008 - Inyector Combustible Circuito D Deficiente",
    keywords: ["p0008", "inyector", "combustible", "circuito d", "obd"],
    answer: "[SIGNIFICADO]\nProbema detectado en el circuito de control del inyector de combustible D (cilindro 4 banco 2). El sistema indica un malfuncionamiento en la inyección de combustible del cilindro correspondiente.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito abierto o intermitente en el inyector D. Inyector defectuoso. Cableado roto o con mala conexión. Conector dañado. Falla en la ECU. Fusible quemado.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del inyector D suelto o desconectado\n- Cableado cortado o dañado\n- Inyector defectuoso o bloqueado\n- Resistencia del inyector fuera de especificación\n- Falla en el conductor del inyector en la ECU\n- Fusible del circuito de inyección quemado\n- Contacto intermitente en los conectores\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Inspeccionar el conector del inyector D\n2. Verificar continuidad del cableado\n3. Medir resistencia del inyector D\n4. Verificar voltaje de alimentación del inyector\n5. Revisar la integridad del fusible de inyección\n6. Probar el patrón de pulso del inyector con osciloscopio\n7. Reemplazar el inyector si es defectuoso\n8. Revisar la ECU si todo lo demás está correcto\n9. Realizar prueba de dinamómetro para confirmar reparación\n[/SOLUCION]"
  },
  {
    title: "OBD P0013 - Árbol Levas Variable B1 Bajo",
    keywords: ["p0013", "árbol levas", "variable", "b1", "bajo", "obd"],
    answer: "[SIGNIFICADO]\nEl sistema de distribución variable de válvulas (VVT) en el banco 1 no está respondiendo correctamente. El árbol de levas está atrasado respecto a lo esperado por el sistema de control.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide VVT defectuoso o atascado. Cableado del solenoide dañado. Aceite del motor sucio o con viscosidad incorrecta. Cadena de distribución estirada. Falta de presión de aceite. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide de control VVT B1 defectuoso\n- Aceite del motor bajo o contaminado\n- Viscosidad del aceite incorrecta\n- Cableado desconectado del solenoide\n- Conector suelto o corrosionado\n- Presión de aceite insuficiente\n- Cadena de distribución gastada\n- Anillo de bloqueo de árbol de levas flojo\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar el nivel y condición del aceite del motor\n2. Cambiar el aceite y filtro si es necesario\n3. Inspeccionar el conector del solenoide VVT\n4. Limpiar o reemplazar el solenoide VVT\n5. Medir la presión de aceite del motor\n6. Revisar la cadena de distribución con luz estroboscópica\n7. Probar el solenoide con voltaje directo (12V)\n8. Verificar la sintonización del árbol de levas con herramienta de diagnóstico\n9. Borrar el código y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0014 - Árbol Levas Variable B1 Alto",
    keywords: ["p0014", "árbol levas", "variable", "b1", "alto", "obd"],
    answer: "[SIGNIFICADO]\nEl árbol de levas variable B1 está adelantado más de lo esperado. El sistema VVT no puede retardar suficientemente el árbol de levas para mantener una sincronización adecuada.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide VVT atascado en posición abierta. Problemas con los conectores del solenoide. Aceite del motor con viscosidad muy alta. Problemas con la cadena de distribución. ECU defectuosa o en cortocircuito.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide VVT B1 atascado o defectuoso\n- Aceite del motor muy viscoso o de grado incorrecto\n- Depósitos de aceite carbonizado en el solenoide\n- Conector del solenoide en cortocircuito\n- Cableado con corto a masa\n- Presión de aceite excesiva\n- Sensor de posición de árbol de levas defectuoso\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar el tipo y grado del aceite del motor\n2. Cambiar a aceite del grado correcto especificado por el fabricante\n3. Limpiar or reemplazar el solenoide VVT B1\n4. Inspeccionar el conector para cortocircuitos\n5. Medir la resistencia del solenoide\n6. Verificar la continuidad del cableado\n7. Revisar la presión de aceite del sistema\n8. Comprobar el sensor CMP (posición de árbol de levas)\n9. Procederá reprogramación de la ECU si es necesario\n[/SOLUCION]"
  },
  {
    title: "OBD P0015 - Árbol Levas Variable B2 Bajo A",
    keywords: ["p0015", "árbol levas", "variable", "b2", "banco 2", "obd"],
    answer: "[SIGNIFICADO]\nEl sistema VVT del banco 2 está presentando problemas de sincronización. El árbol de levas está retrasado más de lo esperado por el sistema de control del motor.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide VVT B2 defectuoso o atascado. Problemas con el cableado del solenoide. Aceite sucio o viscosidad incorrecta. Sensores de posición defectuosos. ECU con problemas.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide VVT B2 defectuoso o bloqueado\n- Aceite del motor contaminado o bajo nivel\n- Viscosidad del aceite incorrecta\n- Cableado desconectado o dañado\n- Conector corrosionado del solenoide\n- Presión de aceite baja\n- Sensor de levas B2 defectuoso\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar nivel y condición del aceite\n2. Cambiar aceite y filtro si es necesario\n3. Limpiar los conectores del solenoide VVT B2\n4. Inspeccionar y limpiar el solenoide\n5. Medir presión de aceite\n6. Probar continuidad del cableado del solenoide\n7. Verificar funcionamiento del sensor CMP B2\n8. Reemplazar componentes defectuosos según resultados\n9. Borrar código de falla y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0016 - Correlación Árbol Levas A Banco 1",
    keywords: ["p0016", "correlación", "árbol levas", "banco 1", "cigüeñal", "obd"],
    answer: "[SIGNIFICADO]\nNo hay correlación adecuada entre la posición del cigüeñal y la posición del árbol de levas en el banco 1. El sistema detecta que estos no están sincronizados correctamente, lo que afecta el control de encendido e inyección.\n[/SIGNIFICADO]\n\n[FALLA]\nSensor de posición de cigüeñal defectuoso. Sensor de árbol de levas defectuoso. Cadena de distribución estirada o rota. Correa de distribución desalineada. Cableado del sensor dañado. Problemas de sincronización de motor.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Sensor CKP (cigüeñal) defectuoso o sucio\n- Sensor CMP (árbol de levas) defectuoso\n- Cadena de distribución estirada o rota\n- Correa de distribución mal sincronizada\n- Cableado de sensores dañado o desconectado\n- Problemas con los conectores de los sensores\n- Anillo de rueda de pulsos dañado\n- Falla en la ECU de control\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar la sincronización visual del motor\n2. Inspeccionar la cadena/correa de distribución\n3. Limpiar los sensores CKP y CMP\n4. Verificar la resistencia de los sensores\n5. Revisar el cableado de ambos sensores\n6. Comprobar los anillos de pulsos\n7. Usar herramienta de diagnóstico para sincronización\n8. Realizar realineación de distribución si es necesario\n9. Reemplazar sensores o cadena según sea requerido\n[/SOLUCION]"
  },
  {
    title: "OBD P0018 - Correlación Árbol Levas A Banco 2",
    keywords: ["p0018", "correlación", "árbol levas", "banco 2", "cigüeñal", "obd"],
    answer: "[SIGNIFICADO]\nProblema de sincronización entre el cigüeñal y el árbol de levas en el banco 2. Los senores detectan que la correlación de posiciones no es la esperada por el sistema.\n[/SIGNIFICADO]\n\n[FALLA]\nSensores de posición defectuosos. Cadena de distribución desgastada. Correa de distribución mal alineada. Cableado de sensores dañado. Conector del sensor desconectado. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Sensor CMP banco 2 defectuoso o excesivamente sucio\n- Sensor CKP defectuoso\n- Cadena de distribución estirada\n- Correa de distribución desalineada\n- Cableado del sensor dañado o cortado\n- Conector del sensor con mal contacto\n- Anillo de pulsos dañado o desgastado\n- Falla en la unidad de control del motor\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Inspeccionar visualmente la cadena/correa de distribución\n2. Verificar sincronización de la distribución\n3. Limpiar los sensores CMP y CKP\n4. Medir resistencia de los sensores\n5. Reviar integridad del cableado de los sensores\n6. Comprobar los conectores para corrosión\n7. Verificar los anillos de pulsos\n8. Usar escáner para leer variables del sistema\n9. Realinear o reemplazar componentes según necesidad\n[/SOLUCION]"
  },
  {
    title: "OBD P0020 - Válvula Control Árbol Levas B Banco 1",
    keywords: ["p0020", "válvula control", "árbol levas", "banco 1", "obd"],
    answer: "[SIGNIFICADO]\nProblema en el sistema de control de la válvula variable del árbol de levas B en el banco 1. El solenoide o el sistema no está respondiendo correctamente a los comandos de la unidad de control.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide de control variable defectuoso. Cableado del solenoide desconectado o dañado. Conector suelto o corrosionado. Aceite del motor contaminado. Problemas con la presión de aceite. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide de control de válvula variable defectuoso\n- Conector del solenoide desconectado\n- Cableado roto o con resistencia alta\n- Aceite del motor con depósitos de carbón\n- Presión de aceite insuficiente\n- Filtro de aceite obstruido\n- Corto a masa en el cableado del solenoide\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar nivel y condición del aceite\n2. Cambiar aceite y filtro si es necesario\n3. Revisar el conector del solenoide\n4. Limpiar el conector y revisar para corrosión\n5. Probar continuidad del cableado del solenoide\n6. Medir resistencia del solenoide\n7. Verificar presión de aceite del motor\n8. Limpiar o reemplazar el solenoide según necesidad\n9. Verificar funcionamiento con escáner después de reparación\n[/SOLUCION]"
  },
  {
    title: "OBD P0022 - Válvula Control Árbol Levas B Banco 1 Bajo",
    keywords: ["p0022", "válvula control", "árbol levas", "bajo", "bank 1", "obd"],
    answer: "[SIGNIFICADO]\nLa válvula de control del árbol de levas B en el banco 1 está funcionando en una posición más retrasada de lo esperado. El sistema no puede avanzar suficientemente el árbol de levas.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide atascado en posición cerrada. Aceite muy viscoso. Presión de aceite baja. Problemas con los conectores. Cableado defectuoso. Falla en la ECU.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide bloqueado o atascado\n- Aceite del motor con viscosidad muy alta\n- Presión de aceite insuficiente\n- Bomba de aceite defectuosa\n- Cableado del solenoide desconectado\n- Conector con mal contacto\n- Falla interna de la ECU\n- Residuos en las válvulas del sistema VVT\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Comprobar el nivel y viscosidad del aceite\n2. Cambiar a aceite con viscosidad correcta\n3. Cambiar aceite y filtro completamente\n4. Verificar presión de aceite del motor\n5. Revisar la bomba de aceite\n6. Inspeccionar conector del solenoide para suciedad\n7. Limpiar los canales de aceite del solenoide\n8. Reemplazar el solenoide si está defectuoso\n9. Probar después de cambio de aceite\n[/SOLUCION]"
  },
  {
    title: "OBD P0024 - Válvula Control Árbol Levas B Banco 2",
    keywords: ["p0024", "válvula control", "árbol levas", "banco 2", "obd"],
    answer: "[SIGNIFICADO]\nProblema en el circuito de control de la válvula variable del árbol de levas B en el banco 2. El sistema detecta funcionamiento anómalo del solenoide de control variable.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide de control variable B banco 2 defectuoso. Cableado del solenoide dañado o desconectado. Conector flojo o corrosionado. Aceite insuficiente o contaminado. Presión de aceite baja. ECU problemática.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide banco 2 defectuoso o bloqueado\n- Conector del solenoide desconectado\n- Cableado roto o con alta resistencia\n- Corto a masa en el circuito del solenoide\n- Aceite del motor bajo o sucio\n- Presión de aceite insuficiente\n- Filtro de aceite obstruido\n- Falla en la salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Cambiar aceite y filtro del motor\n2. Verificar presión de aceite del sistema\n3. Inspeccionar conector del solenoide\n4. Limpiar y revisar el conector para corrosión\n5. Verificar continuidad del cableado\n6. Medir resistencia del solenoide\n7. Probar voltaje al solenoide durante diagnóstico\n8. Limpiar o reemplazar el solenoide\n9. Borrar código y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0026 - Válvula Inyección Aceite Circuito Bajo",
    keywords: ["p0026", "válvula", "inyección aceite", "circuito bajo", "obd"],
    answer: "[SIGNIFICADO]\nProblema detectado en el circuito de control de la válvula de inyección de aceite. El sistema ha registrado un voltaje bajo o ausencia de señal en este circuito.\n[/SIGNIFICADO]\n\n[FALLA]\nVálvula de inyección de aceite defectuosa. Cableado abierto o desconectado. Conector suelto o corrosionado. Fusible quemado. ECU defectuosa. Problemas con la batería.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector de la válvula desconectado\n- Cableado roto o con alta resistencia\n- Válvula de inyección de aceite defectuosa\n- Fusible del circuito quemado\n- Conector con corrosión o mal contacto\n- Batería con voltaje bajo\n- Falla en la salida de la ECU\n- Terminal del alternador desconectado\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje de la batería\n2. Revisar el fusible del circuito\n3. Inspeccionar el conector de la válvula\n4. Limpiar los contactos del conector\n5. Verificar continuidad del cableado\n6. Medir voltaje en la válvula durante operación\n7. Probar la válvula con voltaje directo (12V)\n8. Reemplazar la válvula si es defectuosa\n9. Revisar ECU si todo lo demás está bien\n[/SOLUCION]"
  },
  {
    title: "OBD P0028 - Válvula Inyección Aceite Circuito Alto",
    keywords: ["p0028", "válvula", "inyección aceite", "circuito alto", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje alto detectado en el circuito de control de la válvula de inyección de aceite. El sistema registra un problema de sobre-voltaje en este circuito.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito en cortocircuito a voltaje positivo. Cableado dañado en cortocircuito. Conector defectuoso. Válvula defectuosa con corto interno. ECU con problema. Relé defectuoso.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Cableado del circuito en cortocircuito a positivo\n- Conector dañado o defectuoso\n- Válvula de inyección de aceite en cortocircuito\n- Relé del circuito defectuoso\n- Aislamiento del cable dañado\n- Fusible defectuoso\n- Falla en la ECU del circuito\n- Batería con voltaje elevado (alternador defectuoso)\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje del alternador (debe ser 13.5-14.5V)\n2. Inspeccionar el cableado para aislamiento dañado\n3. Revisar conector para corrosión o daño\n4. Desconectar la válvula y medir voltaje en el conector\n5. Probar la válvula para cortocircuito\n6. Verificar el relé del circuito\n7. Buscar cortocircuitos en todo el arnés\n8. Reemplazar componentes defectuosos\n9. Revisar ECU si todo lo demás está correcto\n[/SOLUCION]"
  },
  {
    title: "OBD P0031 - Calentador O2 B1S1 Circuito Bajo",
    keywords: ["p0031", "o2", "calentador", "b1s1", "circuito bajo", "obd"],
    answer: "[SIGNIFICADO]\nEl sistema ha detectado un voltaje bajo o ausencia de voltaje en el circuito de calentamiento del sensor de oxígeno B1S1. Este sensor necesita alcanzar una temperatura operativa para funcionar correctamente.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito abierto en el elemento calefactor del sensor O2. Conector desconectado o flojo. Cableado roto. Fusible quemado. ECU defectuosa. Relé del calentador defectuoso.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del sensor O2 B1S1 desconectado\n- Cableado del elemento calefactor roto o abierto\n- Elemento calefactor del sensor O2 defectuoso\n- Fusible del circuito quemado\n- Relé del calentador O2 defectuoso\n- Conector corrosionado o con mal contacto\n- Falla en la salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar el fusible del calentador O2\n2. Inspeccionar el conector del sensor O2\n3. Limpiar los contactos del conector\n4. Verificar continuidad del cableado del elemento calefactor\n5. Medir resistencia del elemento calefactor (típicamente 2-14 ohmios)\n6. Medir voltaje en el conector durante arranque\n7. Revisar el relé del calentador O2\n8. Reemplazar sensor si el calefactor está defectuoso\n9. Borrar codigo y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0033 - Válvula Descarga Turbo Solenoide",
    keywords: ["p0033", "válvula descarga", "turbo", "solenoide", "boost", "obd"],
    answer: "[SIGNIFICADO]\nProblema detectado en el circuito de control del solenoide de descarga del turbo. Este componente regula la presión de sobrealimentación del motor turbo.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide de descarga defectuoso o atascado. Cableado desconectado o dañado. Conector flojo o corrosionado. Línea de vacío rota. Diafragma de la válvula dañado. ECU problemática.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide de descarga bloqueado o defectuoso\n- Conector del solenoide desconectado\n- Cableado del solenoide roto o con alta resistencia\n- Corto a masa en el circuito\n- Línea de vacío rota o desconectada\n- Diafragma de la válvula de descarga perforado\n- Depósitos de carbón en el solenoide\n- Falla en la salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar continuidad del cableado del solenoide\n2. Revisar conector para corrosión o daño\n3. Limpiar el conector\n4. Inspeccionar líneas de vacío\n5. Medir resistencia del solenoide\n6. Probar voltaje en el solenoide durante diagnóstico\n7. Revisar presión de boost con medidor de vacío\n8. Limpiar o reemplazar el solenoide\n9. Comprobar diafragma de la válvula de descarga\n[/SOLUCION]"
  },
  {
    title: "OBD P0034 - Válvula Descarga Turbo Rango Alto",
    keywords: ["p0034", "válvula descarga turbo", "alto", "boost", "obd"],
    answer: "[SIGNIFICADO]\nLa válvula de descarga del turbo está abierta excesivamente, resultando en una presión de sobrealimentación mayor de lo esperado. Sistema de control no puede limitar la presión a niveles normales.\n[/SIGNIFICADO]\n\n[FALLA]\nSolenoide atascado en posición abierta. Línea de vacío desconectada. Diafragma perforado. Cableado en cortocircuito. Sensor MAP defectuoso. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide bloqueado en posición abierta\n- Línea de vacío del solenoide desconectada\n- Diafragma de válvula perforado\n- Cableado del solenoide en cortocircuito a positivo\n- Sensor MAP defectuoso mandando señal engañosa\n- Presión de turbo excesiva\n- Falla en el controlador del solenoide en la ECU\n- Válvula de escape del turbo defectuosa\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar presión de turbo con manómetro\n2. Inspeccionar líneas de vacío\n3. Revisar conector del solenoide\n4. Medir voltaje en el solenoide\n5. Verificar resistencia del solenoide\n6. Revisar sensor MAP\n7. Limpiar o reemplazar solenoide de descarga\n8. Inspeccionar válvula de escape del turbo\n9. Reemplazar diafragma si está dañado\n[/SOLUCION]"
  },
  {
    title: "OBD P0037 - Calentador O2 B2S2 Circuito Bajo",
    keywords: ["p0037", "o2", "calentador", "b2s2", "circuito bajo", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje bajo detectado en el circuito del elemento calefactor del sensor de oxígeno en banco 2 sensor 2. Esto afecta la capacidad del sensor para medir emisiones correctamente.\n[/SIGNIFICADO]\n\n[FALLA]\nElemento calefactor del sensor O2 abierto o en cortocircuito. Conector desconectado. Cableado roto. Fusible quemado. Relé defectuoso. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector B2S2 O2 desconectado o suelto\n- Cableado del elemento calefactor abierto\n- Elemento calefactor del sensor O2 defectuoso\n- Fusible del circuito quemado\n- Relé del calentador defectuoso\n- Corrosión en los contactos del conector\n- Falla en el circuito de salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Reemplazar el fusible del calentador O2\n2. Revisar conector del sensor B2S2\n3. Limpiar y verificar contactos\n4. Probar continuidad del cableado del calefactor\n5. Medir resistencia del elemento calefactor\n6. Medir voltaje en el conector durante arranque\n7. Revisar relé del calentador\n8. Reemplazar sensor O2 si es defectuoso\n9. Verificar conexión de tierra del circuito\n[/SOLUCION]"
  },
  {
    title: "OBD P0040 - Sensor O2 Rango Inapropiado",
    keywords: ["p0040", "sensor o2", "rango", "inapropiado", "obd"],
    answer: "[SIGNIFICADO]\nEl sensor de oxígeno está mandando una señal fuera del rango esperado. El sistema no puede interpretar correctamente la composición del escape.\n[/SIGNIFICADO]\n\n[FALLA]\nSensor O2 defectuoso o contaminado. Cableado del sensor dañado. Conector flojo. Corriente de aire falsa en el motor. Inyección de combustible problemática. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Sensor O2 con depósitos de carbón o contaminación\n- Sensor envejecido o defectuoso\n- Cableado del sensor con mala conexión\n- Conector del sensor dañado o corrosionado\n- Corriente de aire falsa reduciendo la mezcla\n- Inyector con fugas\n- Catalizador obstruido\n- Falla en la etapa de entrada de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Desconectar conector del sensor O2\n2. Verificar continuidad del cableado\n3. Medir voltaje de referencia del sensor\n4. Revisar conector para corrosión\n5. Hacer prueba de osciloscopio de la señal del sensor\n6. Verificar integridad del conducto de escape\n7. Probar mezcla de aire/combustible\n8. Reemplazar sensor O2 si es defectuoso\n9. Borrar código y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0042 - Calentador O2 Circuito Bajo Banco 1 Sensor 3",
    keywords: ["p0042", "o2", "calentador", "banco 1", "sensor 3", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje insuficiente en el circuito del elemento calefactor del sensor de oxígeno banco 1 sensor 3. Este sensor típicamente se encuentra en el catalizador.\n[/SIGNIFICADO]\n\n[FALLA]\nElemento calefactor abierto o defectuoso. Conector desconectado. Cableado roto. Fusible quemado. Relé defectuoso. ECU problema.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del sensor O2 B1S3 desconectado\n- Cableado del calefactor roto o abierto\n- Elemento calefactor defectuoso\n- Fusible del circuito quemado\n- Relé del calentador defectuoso\n- Conector corrosionado\n- Falla en la salida ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar y reemplazar fusible si es necesario\n2. Desconectar conector del sensor\n3. Limpiar contactos del conector\n4. Verificar continuidad del cableado\n5. Medir resistencia del elemento calefactor\n6. Medir voltaje en el conector durante arranque\n7. Revisar el relé\n8. Reemplazar sensor si es defectuoso\n9. Hacer prueba de ruta después de reparación\n[/SOLUCION]"
  },
  {
    title: "OBD P0050 - Calentador O2 Circuito Bajo Banco 2 Sensor 1",
    keywords: ["p0050", "o2", "calentador", "banco 2", "sensor 1", "obd"],
    answer: "[SIGNIFICADO]\nProblema de voltaje bajo en el circuito del calentador del sensor de oxígeno banco 2 sensor 1. Este es el sensor previo al catalizador en el banco 2.\n[/SIGNIFICADO]\n\n[FALLA]\nElemento calefactor defectuoso o abierto. Conector desconectado o flojo. Cableado roto. Fusible del circuito quemado. Relé defectuoso. ECU con problema.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del sensor O2 B2S1 desconectado\n- Cableado del calefactor abierto o roto\n- Elemento calefactor del sensor defectuoso\n- Fusible del circuito quemado\n- Relé del calentador defectuoso\n- Corrosión en contactos del conector\n- Falla en salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Reemplazar el fusible del calentador si es necesario\n2. Revisar conector del sensor B2S1\n3. Limpiar contactos del conector\n4. Verificar continuidad del cableado del calefactor\n5. Medir resistencia del elemento calefactor\n6. Medir voltaje en el conector durante arranque\n7. Revisar relé del calentador\n8. Reemplazar sensor si el calefactor está defectuoso\n9. Borrar código y hacer prueba de ruta\n[/SOLUCION]"
  },
  {
    title: "OBD P0052 - Calentador O2 Circuito Bajo Banco 2 Sensor 2",
    keywords: ["p0052", "o2", "calentador", "banco 2", "sensor 2", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje bajo registrado en el circuito del elemento calefactor del sensor de oxígeno banco 2 sensor 2, ubicado después del catalizador.\n[/SIGNIFICADO]\n\n[FALLA]\nCalentador del sensor abierto. Conector desconectado. Cableado dañado. Fusible quemado. Relé defectuoso. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del sensor O2 B2S2 desconectado o suelto\n- Cableado del elemento calefactor abierto\n- Elemento calefactor diagnóstico del sensor defectuoso\n- Fusible del circuito quemado\n- Relé del calentador defectuoso\n- Contactos corrosionados en el conector\n- Falla en la salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Revisar y reemplazar el fusible si es necesario\n2. Inspeccionar conector del sensor B2S2\n3. Limpiar los contactos del conector\n4. Verificar continuidad del cableado del calefactor\n5. Medir resistencia del elemento calefactor\n6. Medir voltaje en el conector durante arranque\n7. Revisar el relé del calentador\n8. Reemplazar sensor si es defectuoso\n9. Borrar código de falla después de reparación\n[/SOLUCION]"
  },
  {
    title: "OBD P0054 - Voltaje Referencia Calentador O2 Bajo",
    keywords: ["p0054", "voltaje referencia", "calentador o2", "bajo", "obd"],
    answer: "[SIGNIFICADO]\nEl voltaje de referencia o control del circuito del elemento calefactor del sensor O2 está más bajo de lo esperado. Afecta la capacidad de calentar apropiadamente el sensor.\n[/SIGNIFICADO]\n\n[FALLA]\nControlador de voltaje defectuoso. Cableado de referencia dañado. Conector suelto. Fusible de referencia quemado. ECU defectuosa. Batería baja.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Voltaje de batería bajo\n- Fusible de referencia quemado\n- Cableado de referencia roto o abierto\n- Conector de referencia desconectado\n- Corrosión en contactos de referencia\n- Regulador de voltaje defectuoso\n- Falla en la ECU\n- Alternador no cargando correctamente\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje de la batería\n2. Revisar voltaje del alternador\n3. Verificar y reemplazar fusible de referencia si es necesario\n4. Revisar continuidad del cableado de referencia\n5. Inspeccionar conectores de referencia\n6. Limpiar contactos corrosionados\n7. Verificar regulador de voltaje\n8. Medir voltaje de referencia en el conector\n9. Reparar alternador o reemplazar batería si es necesario\n[/SOLUCION]"
  },
  {
    title: "OBD P0056 - Calentador O2 Circuito Alto Banco 2 Sensor 2",
    keywords: ["p0056", "o2", "calentador", "banco 2", "sensor 2", "alto", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje excesivo detectado en el circuito del elemento calefactor del sensor O2 banco 2 sensor 2. Indica problemas en el control del voltaje del circuito.\n[/SIGNIFICADO]\n\n[FALLA]\nCircuito en cortocircuito a voltaje positivo. Relé defectuoso. Cableado dañado. Conector defectuoso. ECU defectuosa. Alternador con voltaje alto.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Cableado del calentador en cortocircuito a positivo\n- Conector defectuoso con continuidad defectuosa\n- Relé del calentador defectuoso\n- Aislamiento del cable dañado\n- Alternador cargando con voltaje alto\n- Regulador de voltaje del alternador defectuoso\n- Falla en la ECU del circuito de control\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje del alternador\n2. Inspeccionar cableado para aislamiento dañado\n3. Revisar conector del sensor para cortocircuitos\n4. Verificar continuidad del cableado\n5. Medir voltaje en el conector\n6. Revisar relé del calentador\n7. Buscar cortocircuitos en el arnés\n8. Reemplazar componentes defectuosos\n9. Revisar regulador del alternador\n[/SOLUCION]"
  },
  {
    title: "OBD P0058 - Calentador O2 Circuito Alto Banco 2 Sensor 3",
    keywords: ["p0058", "o2", "calentador", "banco 2", "sensor 3", "alto", "obd"],
    answer: "[SIGNIFICADO]\nEl circuito del elemento calefactor del sensor O2 ubicado en el catalizador del banco 2 está presentando un voltaje superior al esperado.\n[/SIGNIFICADO]\n\n[FALLA]\nCortocircuito a voltaje positivo. Relé defectuoso. Cableado en cortocircuito. Conector defectuoso. ECU defectuosa. Alternador con exceso de voltaje.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Cableado del calentador O2 en cortocircuito a positivo\n- Conector defectuoso\n- Relé del calentador defectuoso\n- Aislamiento del cable dañado o roto\n- Alternador cargando voltaje demasiado alto\n- Regulador de voltaje del alternador defectuoso\n- Falla en control de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje del alternador (debe ser 13.5-14.5V)\n2. Revisar cableado para aislamiento dañado\n3. Inspeccionar conector para cortocircuitos\n4. Desconectar conector del sensor\n5. Medir voltaje en el conector desconectado\n6. Buscar cortocircuitos en el arnés\n7. Verificar relé del calentador\n8. Reemplazar componentes defectuosos\n9. Revisar regulador del alternador\n[/SOLUCION]"
  },
  {
    title: "OBD P0060 - Calentador O2 Circuito Alto Banco 1 Sensor 3",
    keywords: ["p0060", "o2", "calentador", "banco 1", "sensor 3", "alto", "obd"],
    answer: "[SIGNIFICADO]\nVoltaje excesivo en el circuito del elemento calefactor del sensor de oxígeno banco 1 sensor 3 (sensor post-catalizador).\n[/SIGNIFICADO]\n\n[FALLA]\nCortocircuito a voltaje positivo. Relé defectuoso. Cableado defectuoso. Conector dañado. ECU con problema. Alternador cargando excesivamente.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Cableado en cortocircuito a positivo\n- Conector defectuoso\n- Relé del calentador defectuoso\n- Aislamiento del cable dañado\n- Alternador con voltaje alto\n- Regulador de voltaje del alternador defectuoso\n- Falla en control de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje del alternador\n2. Revisar aislamiento del cableado\n3. Inspeccionar conector del sensor\n4. Desconectar conector\n5. Medir voltaje en el conector\n6. Buscar cortocircuitos a positivo\n7. Verificar relé del calentador\n8. Reemplazar componentes defectuosos\n9. Revisar regulador del alternador\n[/SOLUCION]"
  },
  {
    title: "OBD P0062 - Voltaje Referencia Calentador O2 Alto",
    keywords: ["p0062", "voltaje referencia", "calentador o2", "alto", "obd"],
    answer: "[SIGNIFICADO]\nEl voltaje de referencia del circuito del calentador del sensor O2 está más alto de lo especificado. Puede causar sobrecalentamiento del elemento calefactor.\n[/SIGNIFICADO]\n\n[FALLA]\nAlternador cargando excesivamente. Regulador de voltaje defectuoso. Cableado de referencia en cortocircuito. Conector defectuoso. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Voltaje de batería/alternador excesivo\n- Regulador de voltaje del alternador defectuoso\n- Cableado de referencia en cortocircuito a positivo\n- Conector de referencia defectuoso\n- Corto en los cables de referencia\n- Fusible de referencia defectuoso\n- Falla en la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar voltaje del alternador (debe ser 13.5-14.5V)\n2. Revisar conector del alternador\n3. Inspeccionar cableado de referencia\n4. Revisar conector de referencia\n5. Medir continuidad del cableado de referencia\n6. Buscar cortocircuitos a positivo\n7. Verificar fusible de referencia\n8. Revisar regulador de voltaje del alternador\n9. Reemplazar alternador si es necesario\n[/SOLUCION]"
  },
  {
    title: "OBD P0064 - Válvula Control Inyector Combustible Auxiliar",
    keywords: ["p0064", "válvula control", "inyector", "combustible", "auxiliar", "obd"],
    answer: "[SIGNIFICADO]\nProblema detectado en el circuito de control de un inyector de combustible auxiliar. Este tipo de inyectores se usan en sistemas de inyección de combustible de emergencia o sistemas bicombusti\n[/SIGNIFICADO]\n\n[FALLA]\nInyector auxiliar defectuoso. Cableado desconectado o dañado. Conector suelto. Solenoide defectuoso. ECU defectuosa. Fusible quemado.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Conector del inyector auxiliar desconectado\n- Cableado roto o con alta resistencia\n- Inyector defectuoso o bloqueado\n- Solenoide del inyector defectuoso\n- Fusible del circuito quemado\n- Conector corrosionado\n- Falla en la salida de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Verificar fusible del circuito\n2. Revisar conector del inyector auxiliar\n3. Inspeccionar cableado para continuidad\n4. Limpiar conector si hay corrosión\n5. Medir resistencia del inyector\n6. Medir voltaje en el inyector durante operación\n7. Probar inyector con voltaje directo\n8. Reemplazar inyector si es defectuoso\n9. Revisar ECU si todo lo demás está bien\n[/SOLUCION]"
  },
  {
    title: "OBD P0066 - Válvula Evaporativa Purga Circuito",
    keywords: ["p0066", "válvula evaporativa", "purga", "circuito", "evap", "obd"],
    answer: "[SIGNIFICADO]\nProblema detectado en el circuito de la válvula de purga del sistema EVAP. Esta válvula purga los vapores de combustible del carbón activado al motor.\n[/SIGNIFICADO]\n\n[FALLA]\nVálvula de purga defectuosa. Solenoide de purga defectuoso. Cableado desconectado. Conector flojo. Línea de purga bloqueada. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Solenoide de válvula de purga defectuoso\n- Conector del solenoide desconectado\n- Cableado roto o con problema\n- Válvula de purga bloqueada o atascada\n- Línea de purga obstruida\n- Depósitos de carbón en la válvula\n- Falla en la salida de la ECU\n- Conector corrosionado\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Revisar conector del solenoide de purga\n2. Inspeccionar línea de purga\n3. Limpiar líneas de purga si hay obstrucción\n4. Verificar continuidad del cableado\n5. Medir resistencia del solenoide\n6. Medir voltaje en el solenoide\n7. Limpiar o reemplazar válvula de purga\n8. Revisar canister EVAP\n9. Borrar código después de reparación\n[/SOLUCION]"
  },
  {
    title: "OBD P0070 - Línea Combustible Presión Sensor Correlación",
    keywords: ["p0070", "línea combustible", "presión", "sensor", "correlación", "obd"],
    answer: "[SIGNIFICADO]\nEl sensor de presión de la línea de combustible está mostrando valores que no correlacionan con lo esperado por el sistema de control. Indica problemas en la medición de presión del combustible.\n[/SIGNIFICADO]\n\n[FALLA]\nSensor de presión de combustible defectuoso. Cableado del sensor desconectado. Presión de combustible real anómala. Línea de combustible con fugas. Conector suelto. ECU defectuosa.\n[/FALLA]\n\n[POSIBLES CAUSAS]\n- Sensor de presión de combustible defectuoso\n- Conector del sensor desconectado o suelto\n- Cableado del sensor roto o dañado\n- Presión real de combustible anómala\n- Línea de combustible pinchada o rota\n- Regulador de presión de combustible defectuoso\n- Bomba de combustible defectuosa\n- Falla en la entrada de la ECU\n[/POSIBLES CAUSAS]\n\n[SOLUCION]\n1. Inspeccionar conector del sensor de presión\n2. Verificar continuidad del cableado del sensor\n3. Medir voltaje de referencia del sensor\n4. Medir presión real de combustible con manómetro\n5. Revisar línea de combustible para fugas\n6. Revisar regulador de presión de combustible\n7. Probar bomba de combustible\n8. Reemplazar sensor si está defectuoso\n9. Realizar prueba de ruta después de reparación\n[/SOLUCION]"
  }
];

async function loadKnowledgeBase() {
  console.log('Iniciando carga de Knowledge Base - OBD Pack 8...');
  console.log(`Total de articulos a insertar: ${newArticles.length}\n`);

  for (const article of newArticles) {
    try {
      const { error } = await supabase
        .from('assistant_kb')
        .insert([
          {
            title: article.title,
            keywords: article.keywords,
            answer: article.answer,
          }
        ]);

      if (error) {
        console.log(`❌ Error al insertar: ${article.title}`, error.message);
      } else {
        console.log(`✅ Insertado: ${article.title}`);
      }
    } catch (err) {
      console.log(`❌ Error: ${err.message}`);
    }
  }

  console.log(`\n✅ Proceso completado - Pack 8`);
  console.log(`Total procesado: ${newArticles.length} articulos`);
}

loadKnowledgeBase();
