import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const dieselSystemArticles = [
  {
    title: "Sistema de Inyección Diesel Common Rail - Presiones y Especificaciones",
    keywords: ["diesel", "common rail", "inyector", "presión", "bar", "psi", "bomba", "rieles"],
    answer: "[PRESIONES DE OPERACION DIESEL COMMON RAIL]\n\nPresiones Típicas por Generación:\nGeneración 1 (1997-2003):\n- Presión Nominal: 1350 bar (19,600 PSI)\n- Presión Máxima: 1600 bar (23,200 PSI)\n- Presión Mínima Operación: 800 bar (11,600 PSI)\n\nGeneración 2 (2003-2010):\n- Presión Nominal: 1600-1700 bar (23,200-24,600 PSI)\n- Presión Máxima: 2000 bar (29,000 PSI)\n- Presión Mínima Operación: 900 bar (13,000 PSI)\n\nGeneración 3 (2010-actualidad):\n- Presión Nominal: 1800-2000 bar (26,100-29,000 PSI)\n- Presión Máxima: 2500 bar (36,250 PSI)\n- Presión Mínima Operación: 1200 bar (17,400 PSI)\n\nGeneración 4 (2015-actualidad):\n- Presión Nominal: 2000-2500 bar (29,000-36,250 PSI)\n- Presión Máxima: 3000 bar (43,500 PSI)\n- Presión Mínima Operación: 1800 bar (26,100 PSI)\n[/PRESIONES DE OPERACION DIESEL COMMON RAIL]\n\n[ESPECIFICACIONES POR FABRICANTE]\n\nBosch (Principal Suministrador):\n- CP1/CP1H: Hasta 1350 bar\n- CP3/CP3S: Hasta 1600 bar\n- CP4/CP4.2: Hasta 2000 bar\n- CRDi-4: Hasta 2500 bar\n\nDelphi:\n- DPC: 1600 bar\n- DPC-CR: 1800 bar\n- DPC-US: 2000 bar\n\nDenso:\n- HP3: 1600 bar\n- HP4: 2000 bar\n- HP5: 2500 bar\n\nSiemens VDO:\n- VCR: 1600 bar\n- VCS: 1800 bar\n[/ESPECIFICACIONES POR FABRICANTE]\n\n[VOLTAJES DE SOLENOIDE INYECTOR]\nEnergización: 7-14V típicamente\nCorriente: 0.5-2.0 A por inyector\nTiempo de Pulso (Inyección): 0.5-3.0 ms\nRetraso de Inyección: Hasta 50 grados cigüeñal antes de PMS\n[/VOLTAJES DE SOLENOIDE INYECTOR]\n\n[PROCEDIMIENTO DE DIAGNOSTICO]\n1. Presión en Ralentí: debe estar 800-1200 bar\n2. Si es menor: Revisar sensor de presión, bomba, regulador\n3. Presión en Aceleración: debe llegar a especificación máxima\n4. Medir Consumo Inyector: típicamente 0.8 A\n5. Verificar Inyector con Escáner:\n   - Resistencia: 2-4 ohms típicamente\n   - No hacer pulsos en laboratorio (alto voltaje)\n6. Prueba de Fugas de Inyector:\n   - Colectar combustible en vaso de vidrio\n   - 15 minutos motor apagado: no debe gotear\n   - Si gotea: inyector defectuoso (replace, no limpiar)\n[/PROCEDIMIENTO DE DIAGNOSTICO]\n\n[CODIGOS DE FALLA COMUNES]\nP0087: Presión de combustible sistema baja\nP0088: Presión de combustible sistema alta\nP0089: Regulador presión combustible rango abierto\nP0090: Regulador presión combustible rango bajo\nP0091: Regulador presión combustible rango alto\nP0200: Problema genérico inyector combustible\nP0201-P0208: Inyector cilindro específico defectuoso\n[/CODIGOS DE FALLA COMUNES]"
  },
  {
    title: "Turbocompresor Diesel - Presión de Boost y Diagnóstico Técnico",
    keywords: ["turbo", "diesel", "boost", "presión", "bar", "psi", "válvula descarga"],
    answer: "[PRESION DE BOOST TIPICA DIESEL]\n\nMotores Turbo sin Intercooler:\n- Presión Normal: 1.5-2.0 bar (21.7-29 PSI)\n- Presión Máxima Segura: 2.5 bar (36.2 PSI)\n\nMotores Turbo con Intercooler:\n- Presión Normal: 2.0-3.0 bar (29-43.5 PSI)\n- Presión Máxima Segura: 3.5 bar (50.8 PSI)\n\nMotores Twin-Turbo Secuencial:\n- Primer Turbo: 1.2-1.8 bar (17.4-26.1 PSI)\n- Segundo Turbo: 2.5-3.5 bar (36.2-50.8 PSI)\n- Máxima Combinada: 4.0 bar (58 PSI)\n\nMotores Twin-Turbo Paralelo:\n- Presión Normal: 2.5-3.5 bar (36.2-50.8 PSI)\n- Máxima Segura: 4.5 bar (65.3 PSI)\n[/PRESION DE BOOST TIPICA DIESEL]\n\n[PRESION POR TEMPERATURA Y ALTITUD]\nNivel del Mar:\n- 0°C: Presión máxima especificada\n- 20°C: 95% de máxima\n- 40°C: 90% de máxima\n\nAltura 1000m:\n- Presión teórica: -12% comparado nivel del mar\n- Compensación automática en ECU modernas\n\nAltura 2000m:\n- Presión teórica: -24% comparado nivel del mar\n- Algunos vehículos limitan potencia automáticamente\n[/PRESION POR TEMPERATURA Y ALTITUD]\n\n[ESPECIFICACIONES POR FABRICANTE]\n\nGarrett (Principal para Diesel):\n- T3: Hasta 1.8 bar\n- T4: Hasta 2.5 bar\n- T5: Hasta 3.0 bar\n- VGT Series: 2.5-3.5 bar variable\n\nMitsubishi:\n- TD04-7T: 1.8 bar\n- TD05-16G: 2.5 bar\n- TD06-17C: 2.8 bar\n\nHolset:\n- HX30: 1.8 bar\n- HX35: 2.2 bar\n- HX40: 2.8 bar\n- VGT: 3.0-3.5 bar variable\n[/ESPECIFICACIONES POR FABRICANTE]\n\n[DIAGNOSTICO DE PRESION DE BOOST]\n1. Conectar medidor de presión boost en:\n   - Entrada intercooler (si existe)\n   - Salida colector escape antes válvula descarga\n2. En Ralentí: 0.0-0.2 bar (normal)\n3. Acelerar a 2000 RPM:\n   - Debe alcanzar 60-80% de presión nominal\n4. Acelerar a 3000+ RPM:\n   - Debe alcanzar presión especificada\n5. Si no alcanza presión:\n   - Revisar válvula descarga\n   - Revisar inyección de combustible\n   - Revisar integridad del turbo\n6. Si presión es excesiva:\n   - Válvula descarga atascada cerrada\n   - Sensor MAP defectuoso\n   - Solenoide descarga defectuoso\n[/DIAGNOSTICO DE PRESION DE BOOST]\n\n[VÁLVULA DESCARGA (WASTEGATE)]\nVálvula Mecánica:\n- Abre aprox 0.3 bar por encima de nominal\n- Controla automáticamente presión\n- Si falla = presión excesiva\n\nVálvula ELECTRÓNICA (VGT):\n- Controlada por solenoide\n- ECU ajusta posición 0-100%\n- Presión variable según condiciones\n- Código: P0230-P0235 si falla\n[/VÁLVULA DESCARGA (WASTEGATE)]\n\n[CODES OBD COMUNES]\nP0234: Presión boost del motor excesiva\nP0299: Presión boost insuficiente\nP0230-P0235: Problemas solenoide descarga boost\nP0401: Flujo EGR insuficiente (relacionado turbo)\n[/CODES OBD COMUNES]"
  },
  {
    title: "Válvula EGR Diesel - Flujo y Especificaciones Técnicas",
    keywords: ["egr", "recirculación gases", "diesel", "voltaje", "flujo", "válvula", "solenoide"],
    answer: "[ESPECIFICACIONES VALVULA EGR DIESEL]\n\nRango de Flujo:\n- Mínimo (cerrada): 0-2% del flujo aire\n- Normal Operación: 5-15% flujo aire\n- Máximo (abierta): 20-25% flujo aire\n\nPresión de Operación:\n- Entrada exhaust: 1.0-1.5 bar (14.5-21.7 PSI)\n- Control: Mediante válvula reguladora y solenoide\n- Modulación: 0-100% en 256 pasos típicamente\n[/ESPECIFICACIONES VALVULA EGR DIESEL]\n\n[VOLTAJES DE SOLENOIDE EGR]\nAlimentación: 7-14V típicamente\nCorriente: 0.3-1.5 A\nDuty Cycle: 0-100% (modulación PWM)\nFrecuencia PWM: 10-100 Hz (varía por fabricante)\nResistencia Solenoide: 6-15 ohms\n[/VOLTAJES DE SOLENOIDE EGR]\n\n[SENSOR DE POSICION VALVULA]\nTipo: Potenciómetro lineal o LVDT\nAlimentación: 5V típicamente\nSalida:\n- Válvula Cerrada: 0.5-1.0V\n- Válvula Abierta 50%: 2.5V\n- Válvula Completamente Abierta: 4.0-4.5V\nResolución: 0.02V típicamente\n[/SENSOR DE POSICION VALVULA]\n\n[DIAGNOSTICO DE EGR]\n1. Leer presión exhaust con manómetro:\n   - Ralentí: 0.2-0.4 bar\n   - Carga: 1.0-1.5 bar\n2. Verificar continuidad línea EGR\n3. Medir voltaje de solenoide:\n   - Engine OFF: 0V\n   - Neutral ralentí: 0-20V modulado\n   - Aceleración: 30-80V modulado\n4. Verificar sensor posición:\n   - Debe estar entre 0.5V-4.5V\n   - Cambiar linealmente con comando de ECU\n5. Revisar líneas EGRC (cooler):\n   - No debe haber fugas de refrigerante\n   - No debe haber bloqueos\n[/DIAGNOSTICO DE EGR]\n\n[PROBLEMAS COMUNES]\nVálvula Atascada Abierta:\n- Presión exhaust en entrada baja\n- Pérdida de potencia\n- Humo negro en aceleración\n- Código: P0401\n\nVálvula Atascada Cerrada:\n- Altas emisiones NOx\n- Ruido de detonación\n- Temperatura exhaust alta\n- Código: P0402\n\nSolenoide Defectuoso:\n- Válvula no responde a comandos\n- Posición errática\n- Código: P0405-P0407\n\nCooler EGR Bloqueado:\n- Refrigerante no circula\n- Válvula se sobrecalienta\n- Falla tras minutos de funcionamiento\n- Código: P0401 o P0403\n[/PROBLEMAS COMUNES]\n\n[MANTENIMIENTO EGR]\nLimpieza recomendada cada 200,000 km:\n1. Desconectar válvula del motor\n2. Sumergir en disolvente diesel\n3. Limpiar interior cuidadosamente\n4. NO usar cepillo metálico\n5. Revisar sensor de posición\n6. Instalar juntas nuevas\n7. Resellar y reconectar\nNota: En algunos motores es más fácil reemplazar\n[/MANTENIMIENTO EGR]"
  },
  {
    title: "Filtro de Partículas Diésel (DPF) - Regeneración y Diagnóstico",
    keywords: ["dpf", "filtro partículas", "diesel", "regeneración", "presión", "temperatura"],
    answer: "[ESPECIFICACIONES DPF]\n\nTamaño de Poro: 10-100 micrones\nCapacidad de Regeneración:\n- Pasiva: Cuando T exhaust >600°C continuamente\n- Activa: Requiere inyección extra de combustible\n- Forzada: Iniciada por ECU periódicamente\n\nPresión Máxima Diferencial: 50-100 mbar (0.5-1.0 kPa)\nTemperatura Máxima: 900°C\nTemperatura Regeneración Activa: 600-750°C\n[/ESPECIFICACIONES DPF]\n\n[SENSORES DPF]\n\nSensor Presión Diferencial:\n- Alimentación: 5V\n- Salida: 0-5V análogo\n- Rango: 0-100 mbar\n- 0V = sin partículas\n- 4.5V = máximo nivel partículas (~65g)\n\nSensor Temperatura DPF:\n- Tipo: Termistor NTC\n- Rango: -40°C a +1000°C\n- Ubicación: Entrada y salida DPF\n- Señal a ECU para iniciar regeneración\n[/SENSORES DPF]\n\n[PROCESO DE REGENERACION PASIVA]\n1. Conducción normal en autopista\n2. Temperatura exhaust >600°C continuamente\n3. Partículas se queman automáticamente\n4. Regeneración completa: 30-60 minutos\n5. No requiere intervención usuario\n6. Presión diferencial vuelve a normal\n[/PROCESO DE REGENERACION PASIVA]\n\n[PROCESO DE REGENERACION ACTIVA]\n1. ECU detecta presión DPF >80 mbar\n2. Reduce inyección principal\n3. Inyecta extra combustible en exhaust\n4. Catalítico post-DPF quema combustible\n5. Genera calor 600-750°C\n6. Quema partículas en DPF\n7. Duración: 5-15 minutos\n8. Usuario siente:\n   - Mayor consumo combustible\n   - Vibración ligera\n   - Ruido mayor motor\n   - Temperatura de acelerador más alta\n[/PROCESO DE REGENERACION ACTIVA]\n\n[DIAGNOSTICO DPF]\nLectura Verde (Normal):\n- Presión DPF: 0-30 mbar\n- No requiere acción\n\nLectura Amarilla (Precaución):\n- Presión DPF: 30-80 mbar\n- Llevar a carretera para regeneración pasiva\n- Acelerar en marcha sostenida\n\nLectura Roja (Precaución Extrema):\n- Presión DPF: >80 mbar\n- Luz de DPF rojo en panel\n- Sistema inicia regeneración activa automáticamente\n- Usuario debe manejar en condiciones seguras\n[/DIAGNOSTICO DPF]\n\n[PROBLEMAS COMUNES]\nDPF Bloqueado:\n- Presión diferencial >100 mbar permanente\n- Regeneraciones frecuentes no resuelven\n- Causas: Turbo defectuoso, inyección mala\n- Solución: Limpiar o reemplazar DPF\n\nSensor Presión Defectuoso:\n- Lectura errática o fuera de rango\n- Regeneración inadecuada\n- Código P0401-P0403, P0545\n\nLimpieza/Regeneración No Completa:\n- Conducción urbana (baja temperatura exhaust)\n- Regeneración iniciada pero interrumpida\n- Combustible de mala calidad\n[/PROBLEMAS COMUNES]\n\n[RECOMENDACIONES]\nConducción Óptima para DPF:\n- 1-2 veces por semana: conducción en carretera\n- Mantener motor >2500 RPM durante 15+ minutos\n- Uso combustible diésel de calidad\n- Cambio de aceite y filtro cada 10,000 km\n- Revisar presión DPF cada 20,000 km\n[/RECOMENDACIONES]"
  },
  {
    title: "Bombas de Inyección Diésel - Tipos y Especificaciones de Presión",
    keywords: ["bomba inyección", "diesel", "presión", "rotativa", "en línea", "common rail"],
    answer: "[TIPOS DE BOMBAS DIESEL]\n\nBomba Rotativa (Tapa Distribuidora):\n- Presión: 300-500 bar (4,350-7,250 PSI)\n- Caudal: 20-100 cc/min\n- RPM: 500-6000\n- Antigüedad: Típica en motores pre-2000\n- Diseño: Un émbolo oscilante + rotor dosificador\n\nBomba En Línea:\n- Presión: 400-700 bar (5,800-10,150 PSI)\n- Caudal: 50-200 cc/min\n- RPM: 500-6000\n- Antigüedad: 1980s-1990s\n- Diseño: Émbolos paralelos, uno por cilindro\n\nBomba de Inyección Directa (DI):\n- Presión: 600-1000 bar (8,700-14,500 PSI)\n- Caudal: 100-300 cc/min\n- RPM: 500-6000\n- Antigüedad: 1990s-2000s\n- Diseño: Bomba en cabezote + tuberías cortas\n\nBomba Common Rail (Actual):\n- Presión: 1600-3000 bar (23,200-43,500 PSI)\n- Caudal: Alta demanda variable\n- RPM: 500-6000\n- Diseño: Bomba genera alta presión constantemente\n- Control: Solenoide regulador mantiene presión\n[/TIPOS DE BOMBAS DIESEL]\n\n[DIAGNOSTICO DE PRESION ROTATIVA]\n1. Presión Baja (100-200 bar):\n   - Bomba desgastada plungers\n   - Regulador de presión defectuoso\n   - Filtro obstruido\n   - Retardo en aceleración\n\n2. Presión Normal (300-500 bar):\n   - Motor arranca rápido\n   - Aceleración suave\n   - Emisiones normales\n\n3. Presión Excesiva (600+ bar):\n   - Regulador atascado\n   - Inyectores pueden dañarse\n   - Vibración motor\n[/DIAGNOSTICO DE PRESION ROTATIVA]\n\n[DIAGNOSTICO DE PRESION EN LINEA]\n1. Punto de Medición:\n   - Línea salida bomba (antes de tuberías)\n   - Conector de diagnóstico (si existe)\n\n2. Presión Ralentí: 100-200 bar\n3. Presión 2000 RPM: 300-400 bar\n4. Presión 3000 RPM: 500-600 bar\n5. Presión 4000 RPM: 600-700 bar\n\n6. Si Presión Baja:\n   - Revisar inyectores para fugas\n   - Revisar tuberías para grietas\n   - Revisar regulador presión\n   - Revisar bomba de combustible\n\n7. Si No Hay Presión:\n   - Revisar fusible bomba\n   - Revisar conector bomba\n   - Revisar líneas entrada\n   - Bomba defectuosa (reemplazo)\n[/DIAGNOSTICO DE PRESION EN LINEA]\n\n[CÓDIGOS DE FALLA COMÚN]\nP0087: Presión combustible baja\nP0088: Presión combustible alta\nP0089: Abierto regulador presión\nP0090: Regulador presión bajo\nP0091: Regulador presión alto\n[/CÓDIGOS DE FALLA COMÚN]\n\n[MANTENIMIENTO]\nCambio Filtro Combustible: Cada 10,000-15,000 km\nLimpieza Inyectores: Cada 80,000-100,000 km\nRevisión Regulador: Cada 200,000 km\nReemplazo Bomba: 300,000-500,000 km típicamente\nUso Combustible:\n- Diésel de calidad es crítico\n- Evitar combustible contaminado\n- Usar aditivos cada 50,000 km\n[/MANTENIMIENTO]"
  }
];

async function loadDieselArticles() {
  console.log('Iniciando carga de Sistemas Diesel Precisos...');
  console.log(`Total de articulos a insertar: ${dieselSystemArticles.length}\n`);

  for (const article of dieselSystemArticles) {
    try {
      const { error } = await supabase
        .from('assistant_kb')
        .insert([
          {
            title: article.title,
            keywords: article.keywords,
            answer: article.answer,
          }
        ]);

      if (error) {
        console.log(`❌ Error al insertar: ${article.title}`, error.message);
      } else {
        console.log(`✅ Insertado: ${article.title}`);
      }
    } catch (err) {
      console.log(`❌ Error: ${err.message}`);
    }
  }

  console.log(`\n✅ Proceso completado - Sistemas Diesel Precisos`);
  console.log(`Total procesado: ${dieselSystemArticles.length} articulos`);
}

loadDieselArticles();
