import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

const precisionSensorArticles = [
  {
    title: "Sensor ECT (Temperature Engine Coolant) - Especificaciones Técnicas Precisas",
    keywords: ["ect", "coolant", "temperatura", "sensor", "ntc", "termistor", "resistencia", "voltaje"],
    answer: "[ESPECIFICACIONES ELECTRICAS]\nTipo: Termistor NTC (Negative Temperature Coefficient)\nRango de Temperatura: -40°C a +130°C\nRango de Resistencia Nominal:\n- A 0°C: 2200-2700 ohms (varia por fabricante)\n- A 20°C: 1000-1200 ohms\n- A 50°C: 300-350 ohms\n- A 80°C: 100-150 ohms\n- A 100°C: 40-80 ohms\n- A 120°C: 20-30 ohms\n[/ESPECIFICACIONES ELECTRICAS]\n\n[VOLTAJE EN CONECTOR]\n- A 0°C: Aprox 4.5V (con pull-up de 5V)\n- A 20°C: Aprox 3.0V\n- A 50°C: Aprox 1.5V\n- A 100°C: Aprox 0.5V\nTiempo de respuesta: 1-2 segundos\n[/VOLTAJE EN CONECTOR]\n\n[UBICACION POR FABRICANTE]\nFord: Lado paso de rueda derecha, en bloque de motor\nGM: Cerca de termostato, lado pasajero\nToyota: Bajo colector de escape\nHonda: Lado derecho del motor\nVolkswagen: Lado izquierdo, cerca de bomba agua\nMercedes: Debajo de DAM\nBMW: En carcasa termostato\n[/UBICACION POR FABRICANTE]\n\n[DIAGNOSTICO PRECISO]\n1. Desconectar conector del sensor\n2. Medir resistencia con multímetro óhmetro\n3. Calentar sensor con secador de aire (NO agua caliente)\n4. Observar cambio de resistencia en tiempo real\n5. La resistencia DEBE disminuir al calentar (NTC)\n6. Si no cambia = sensor defectuoso\n7. Medir voltaje de señal en conector del ECU\n8. Debe estar entre 0.5V-4.5V según temperatura\n[/DIAGNOSTICO PRECISO]\n\n[TOLERANCIA DE FALLA]\n- Aumento de consumo: >15% indica sensor defectuoso\n- Ralentí inestable: fluctuaciones >100 RPM\n- Temperatura mostrada en panel incorrecta\n- El código de falla debe ser P0117 (bajo) o P0118 (alto)\n[/TOLERANCIA DE FALLA]\n\n[REEMPLAZO]\n1. Esperar motor frío (5-10 minutos después de apagar)\n2. Drenar 1-2 litros de refrigerante\n3. Desconectar conector\n4. Sacar sensor con llave 19mm típicamente\n5. Instalar nuevo con teflón en rosca\n6. Rellenar refrigerante\n7. Purgar aire del sistema\n8. Borrar códigos de falla\n9. Hacer prueba de arranque y ruta\n[/REEMPLAZO]"
  },
  {
    title: "Sensor MAF (Mass Air Flow) - Especificaciones Técnicas Detalladas",
    keywords: ["maf", "flujo aire", "temperatura aire", "sensor", "voltaje", "gramos segundo"],
    answer: "[ESPECIFICACIONES OPERACIONALES]\nRango de Medición: 0-300 g/s (gramos por segundo)\nVoltaje de Referencia: 5V ±0.1V\nTiempo de Respuesta: <100 ms (milisegundos)\nToleancia de Error: ±2% en condiciones normales\nTemperatura de Operación: -40°C a +125°C\n[/ESPECIFICACIONES OPERACIONALES]\n\n[VOLTAJE DE SALIDA NOMINAL]\nIdle (Ralentí): 0.7-1.0V\nAceleración Suave: 1.5-2.0V\nAceleración Media: 2.5-3.5V\nAceleración Máxima: 3.8-4.5V\nCorte de Inyección: >4.5V\n[/VOLTAJE DE SALIDA NOMINAL]\n\n[LECTURA EN g/s POR VOLTAJE]\n0.5V = 2-3 g/s\n1.0V = 5-7 g/s\n2.0V = 15-20 g/s\n3.0V = 30-40 g/s\n4.0V = 50-70 g/s\n4.5V = 100+ g/s\n[/LECTURA EN g/s POR VOLTAJE]\n\n[TIPOS DE SENSORES]\nSensor Hilo Caliente (Hot Wire):\n- Resistencia: 2.5-6 ohms a temperatura operacional\n- Temperatura de trabajo: 200°C\n- Más sensible, detección rápida\n\nSensor Película Delgada (Hot Film):\n- Resistencia: variable según modelo\n- Temperatura de trabajo: 160°C\n- Más preciso, menos propenso a ensuciarse\n[/TIPOS DE SENSORES]\n\n[DIAGNOSTICO PRECISO]\n1. En ralentí: voltaje debe estar 0.7-1.0V (NO es ramp up)\n2. Acelerar suavemente: voltaje debe subir suavemente sin saltos\n3. Si sube bruscamente: sensor defectuoso\n4. Si tiene histéresis (rezago): sensor sucio o defectuoso\n5. Leer volumen de aire en g/s con escáner\n6. Debe ser consistente, sin fluctuaciones\n7. Comparar con presión MAP (debe ser correlacionado)\n[/DIAGNOSTICO PRECISO]\n\n[LIMPIEZA (No reemplazo)]\n1. Desconectar conector del sensor\n2. Sacar sensor del ducto (tuerca de 10mm)\n3. Limpiar SOLO el hilo/película con aire comprimido seco\n4. NUNCA tocar el alambre con dedo\n5. NUNCA usar liquidos de limpieza\n6. NUNCA sumergir en agua\n7. Reinstalar con cuidado\n8. Esperar 2 minutos antes de arrancar motor\n[/LIMPIEZA (No reemplazo)]\n\n[FALLAS COMUNES]\nSensor Sucio: Lectura baja en g/s, pobre aceleration\nSensor Roto: Voltaje fijo o fuera de rango\nConector Flojo: Lectura errática, código intermitente\nResistor Defectuoso (pull-up): Voltaje bajo permanente\nUnidad Calentadora Defectuosa: Sensor no se calienta\n[/FALLAS COMUNES]"
  },
  {
    title: "Sensor MAP (Manifold Absolute Pressure) - Especificaciones Técnicas Avanzadas",
    keywords: ["map", "presión manifold", "sensor", "kpa", "psi", "boost", "voltaje"],
    answer: "[ESPECIFICACIONES DE PRESIÓN]\nRango Típico: 10-105 kPa (1.45-15.2 PSI) en aspirado\nRango Turbo: 10-300+ kPa (1.45-43+ PSI) en sobrealimentado\nVoltaje de Referencia: 5V ±0.1V\nSalida Analógica: 0-5V (algunos modelos 0-10V)\nResolución: 0.02 kPa típicamente\n[/ESPECIFICACIONES DE PRESIÓN]\n\n[VOLTAJE vs PRESION (ASPIRADO)]\n0.4V = 10 kPa (4500m altitud)\n0.9V = 20 kPa\n1.5V = 30 kPa\n2.0V = 40 kPa\n2.5V = 50 kPa (ralentí nivel del mar)\n3.0V = 60 kPa\n3.5V = 70 kPa\n4.0V = 80 kPa\n4.5V = 100 kPa (WOT nivel del mar)\n[/VOLTAJE vs PRESION (ASPIRADO)]\n\n[VOLTAJE vs PRESION (TURBO/SUPERCHARGED)]\n0.5V = 10 kPa\n1.0V = 30 kPa\n1.5V = 50 kPa\n2.0V = 80 kPa\n2.5V = 120 kPa (3.7 PSI boost)\n3.0V = 160 kPa (7.5 PSI boost)\n3.5V = 200 kPa (14.5 PSI boost)\n4.0V = 250 kPa (21.6 PSI boost)\n4.5V = 300+ kPa (43+ PSI boost)\n[/VOLTAJE vs PRESION (TURBO/SUPERCHARGED)]\n\n[DIAGNOSTICO EN RALENTI]\nNivel del Mar: 4.5-5.0V (93-105 kPa)\n500m altitud: 4.0-4.5V (85-93 kPa)\n1000m altitud: 3.8-4.3V (80-90 kPa)\n2000m altitud: 3.2-3.8V (65-78 kPa)\nSi no es Voltaje esperado por altitud = defecto\n[/DIAGNOSTICO EN RALENTI]\n\n[DIAGNOSTICO EN ACELERACION]\n1. En ralentí: voltaje nominal por altitud\n2. Acelerar lentamente: voltaje debe aumentar de forma lineal\n3. Si salta o tiene histéresis: sensor defectuoso\n4. En WOT (Wide Open Throttle):\n   - Aspirado: 4.5V máximo\n   - Turbo 1 bar: ~2.5V\n   - Turbo 1.5 bar: ~3.0V\n   - Turbo 2 bar: ~3.5V\n5. Presión debe seguir aceleración del pedal\n[/DIAGNOSTICO EN ACELERACION]\n\n[MANGUERA DE VACIO]\nInspeccionar cada 12 meses:\n- Grietas o perforaciones\n- Desconexiones\n- Endurecimiento del material\n- Porosidad en manguera (pinchazos)\nReemplazar si es necesario (típicamente cada 50,000 km)\n[/MANGUERA DE VACIO]\n\n[LIMPIEZA DEL SENSOR]\n1. Despressurizar sistema de combustible\n2. Desconectar manguera de vacío\n3. Desconectar conector eléctrico\n4. Sacar sensor (tornillo 10mm típicamente)\n5. Soplar con aire comprimido SECO\n6. NUNCA sumergir en agua\n7. NUNCA tocar diafragma interno\n8. Reinstalar y conectar\n[/LIMPIEZA DEL SENSOR]"
  },
  {
    title: "Sensor IAT (Intake Air Temperature) - Especificaciones Técnicas Precisas",
    keywords: ["iat", "temperatura aire entrada", "ntc", "sensor", "resistencia", "voltaje"],
    answer: "[ESPECIFICACIONES ELECTRICAS]\nTipo: Termistor NTC (Negative Temperature Coefficient)\nRango: -40°C a +120°C\nVoltaje de Referencia: 5V\nResistencia Nominal:\n- A -40°C: 100,000+ ohms\n- A 0°C: 10,000-15,000 ohms\n- A 20°C: 2,200-2,700 ohms\n- A 50°C: 300-400 ohms\n- A 80°C: 70-100 ohms\n- A 120°C: 10-15 ohms\n[/ESPECIFICACIONES ELECTRICAS]\n\n[VOLTAJE EN CONECTOR]\n- A -40°C: 4.8V\n- A 0°C: 3.8-4.2V\n- A 20°C: 2.5-3.0V\n- A 50°C: 1.2-1.5V\n- A 80°C: 0.4-0.6V\n- A 100°C: 0.2-0.3V\n[/VOLTAJE EN CONECTOR]\n\n[UBICACION POR FABRICANTE]\nFord: En tubo de aire, antes del MAF\nGM: En caja de aire o ducto de entrada\nToyota: Integrado en MAF (algunos modelos)\nHonda: En conducto de aire frio\nVolkswagen: En intercooler outlet (turbo)\nMercedes: En tanque de aire\nBMW: En carcasa de aire\n[/UBICACION POR FABRICANTE]\n\n[DIAGNOSTICO]\n1. Motor frío: Voltaje debe ser alto (3.5-4.5V Aprox)\n2. A los 5 minutos funcionando: Voltaje debe bajar\n3. En ralentí caliente: 0.8-1.2V típicamente\n4. Medir resistencia con motor apagado\n5. Calentador aire: voltaje debe aumentar nuevamente\n6. Si no cambia = defectuoso\n7. Verificar cambio de resistencia en tiempo real\n[/DIAGNOSTICO]\n\n[RANGO ACEPTABLE DE ERROR]\nDesviación de ±10°C es aceptable\nDesviación de ±20°C = límite máximo antes de código\nMayor desviación = sensor defectuoso\n[/RANGO ACEPTABLE DE ERROR]\n\n[IMPORTANCIA EN TUNING]\nAire frío = más denso = lectura baja de temperatura\nMotor ajusta mezcla MÁS RICA (más combustible)\nAire caliente = menos denso = lectura alta\nMotor ajusta mezcla MÁS POBRE (menos combustible)\nSensor defectuoso causa falla en ciertos ambientes\n[/IMPORTANCIA EN TUNING]\n\n[REEMPLAZO]\n1. Desconectar conector\n2. Sacar sensor con llave 19-22mm\n3. Instalar nuevo con teflón en rosca (si aplica)\n4. Conectar conector\n5. NO requiere calibración\n6. Borrar códigos de falla\n7. Realizar prueba de ruta\n[/REEMPLAZO]"
  },
  {
    title: "Sensor O2 (Oxygen Lambda) - Especificaciones Técnicas Precisas",
    keywords: ["o2", "lambda", "oxígeno", "sensor", "voltaje", "milivolts", "wideband", "narrowband"],
    answer: "[TIPOS Y ESPECIFICACIONES]\n\nSensor NarrowBand (Convencional):\nRango: 0-1V\nVoltaje Alto (Rica, <14.7:1): 0.7-0.9V\nVoltaje Bajo (Pobre, >14.7:1): 0.1-0.3V\nVoltaje Transición: 0.45-0.55V (punto de conmutación)\nRespuesta: 100-200 ms\nCalefactor: 10-14V, 0.5-2A\n\nSensor WideBand (Banda Ancha):\nRango: 0-5V (algunos 0-10V)\nRango de Medición: 8:1 a 18:1 relación aire/combustible\nPrecisión: ±0.5% en todo el rango\nRespuesta: <100 ms\nCalefactor: 7.5-14V, 0.8-2A\n[/TIPOS Y ESPECIFICACIONES]\n\n[VOLTAJE NARROWBAND vs RELACION A/F]\n0.1V = Muy pobre (16:1 a 18:1)\n0.2V = Pobre (15:1)\n0.3V = Pobre (14.8:1)\n0.45V = Punto transición\n0.6V = Rica (13.5:1)\n0.7V = Muy rica (13:1)\n0.8V = Extremadamente rica (12:1)\n[/VOLTAJE NARROWBAND vs RELACION A/F]\n\n[VOLTAJE WIDEBAND vs RELACION A/F]\n0.5V = 20:1 (muy pobre)\n1.0V = 18:1 (pobre)\n1.5V = 16:1 (mezcla pobre)\n2.0V = 14.7:1 (estequiométrico PERFECTO)\n2.5V = 13:1 (mezcla rica)\n3.0V = 12:1 (rica)\n3.5V = 11:1 (muy rica)\n4.0V = 10:1 (extremadamente rica)\n[/VOLTAJE WIDEBAND vs RELACION A/F]\n\n[PROCEDIMIENTO DE MEDICION]\n1. Desconectar conector del sensor O2\n2. Poner ohmetro en 200 ohms (resistencia)\n3. Elemento calefactor: 4-14 ohms típicamente\n4. Si >15 ohms = probablemente defectuoso\n5. Con motor en marcha (conector conectado):\n   - NarrowBand: medir voltaje oscilante 0.2V-0.8V\n   - WideBand: medir voltaje estable ~2.5V en ralentí\n6. Acelerar suavemente:\n   - N-Band: debe oscilar más rápido\n   - W-Band: debe ser estable cerca de 2.0V\n[/PROCEDIMIENTO DE MEDICION]\n\n[TIEMPO DE CALENTAMIENTO]\nMotor frío: Sensor O2 genera voltaje débil\nAprox 30-45 segundos: Sensor comienza a calentar\nAprox 60-90 segundos: Alcanza temperatura operacional\nLuego: Voltaje fuerte y estable\nSi no se calienta en 2 minutos = calefactor defectuoso\n[/TIEMPO DE CALENTAMIENTO]\n\n[UBICACION POR FABRICANTE]\nFord: 2-3 metros desde motor en catalizador\nGM: Integrado cerca del colector escape\nToyota: Antes y después del catalizador\nHonda: En cabezote, lado colector\nVolkswagen: En múltiple escape\nMercedes: En tubo de escape pre-catalizador\nBMW: En catalizador integrado\n[/UBICACION POR FABRICANTE]\n\n[VIDA UTIL]\nTípicamente: 50,000-100,000 km\nClimas cálidos: 40,000-60,000 km\nCombustible contaminado: acorta vida útil\nReemplazar preventivamente cada 80,000 km\n[/VIDA UTIL]"
  },
  {
    title: "Sensor TPS (Throttle Position Sensor) - Especificaciones Técnicas Precisas",
    keywords: ["tps", "posición acelerador", "sensor", "voltaje", "voltios", "potenciómetro"],
    answer: "[ESPECIFICACIONES ELECTRICAS]\nTipo: Potenciómetro lineal o rotativo\nRango de Voltaje: 0-5V (típicamente)\nTiempo de Respuesta: <10 ms\nRango de Rotación: 0-125° típicamente\nTipo de Contacto: Película de carbón o película de silicio\nVida Útil Especificada: >1,000,000 ciclos\n[/ESPECIFICACIONES ELECTRICAS]\n\n[VOLTAJE vs POSICION DE ACELERADOR]\nCerrado (Idle): 0.5-1.0V\n5% abierto: 1.2-1.5V\n25% abierto: 1.8-2.3V\n50% abierto: 2.4-2.8V\n75% abierto: 3.2-3.8V\n100% abierto (WOT): 4.0-4.8V\n[/VOLTAJE vs POSICION DE ACELERADOR]\n\n[REFERENCIA DE CALIBRACION]\nVoltaje de referencia: 5.0V ±0.1V\nVoltaje mínimo (Cerrado): 0.5V típico\nVoltaje máximo (WOT): 4.8V típico\nHisterésis máxima aceptable: 0.1V\n[/REFERENCIA DE CALIBRACION]\n\n[DIAGNOSTICO PRECISO]\n1. Acelerador COMPLETAMENTE CERRADO: 0.5-1.0V\n2. Si es diferente = recalibración necesaria\n3. Motor apagado, desconectar sensor\n4. Medir resistencia entre todos los pines\n5. Resistencia debe ser lineal vs rotación\n6. Con llave ON (motor apagado):\n   - Voltaje de referencia: 5V en pin de alimentación\n   - Tierra: 0V en pin de tierra\n   - Señal: 0.5-1.0V acelerador cerrado\n7. Mover acelerador suavemente:\n   - Voltaje DEBE cambiar linealmente\n   - Si salta o tiene gaps = defectuoso\n   - Si es lento = contacto deficiente\n[/DIAGNOSTICO PRECISO]\n\n[RANGO DE FALLA]\nSi voltaje está fuera de rango especificado por >0.2V = código P0122 o P0123\nFluctuación excesiva (>0.3V en ralentí) = sensor defectuoso\nNo hay cambio al mover acelerador = potenciómetro abierto\n[/RANGO DE FALLA]\n\n[UBICACION POR FABRICANTE]\nFord: En cuerpo de acelerador\nGM: Integrado en cuerpo de acelerador electrónico\nToyota: En tubo de admisión o cuerpo acelerador\nHonda: En válvula mariposa\nVolkswagen: Acelerador electrónico (ETCS)\nMercedes: Sistema ByWire (sin cable mecánico)\nBMW: Acelerador electrónico sin cable\n[/UBICACION POR FABRICANTE]\n\n[TIPOS MODERNOS]\nDrive-By-Wire (Sin cable): TPS reemplazado por sensor de pedal\nMultiples sensores: 2-3 sensores para redundancia\nIntegrado en cuerpo: Sensor parte del cuerpo acelerador\nRedundancia: 2 canales totalmente independientes\n[/TIPOS MODERNOS]\n\n[REEMPLAZO]\n1. Desconectar conector\n2. Sacar tornillos de montaje (3-4 tornillos)\n3. Desconectar cable mecánico si aplica\n4. Instalar nuevo sensor alineado\n5. Conectar cable nuevamente\n6. Calibrar TPS con herramienta de diagnóstico\n7. Borrar códigos de falla\n8. Realizar prueba de ruta\n[/REEMPLAZO]"
  }
];

async function loadSensorArticles() {
  console.log('Iniciando carga de Sensores Precisos - Pack Técnico...');
  console.log(`Total de articulos a insertar: ${precisionSensorArticles.length}\n`);

  for (const article of precisionSensorArticles) {
    try {
      const { error } = await supabase
        .from('assistant_kb')
        .insert([
          {
            title: article.title,
            keywords: article.keywords,
            answer: article.answer,
          }
        ]);

      if (error) {
        console.log(`❌ Error al insertar: ${article.title}`, error.message);
      } else {
        console.log(`✅ Insertado: ${article.title}`);
      }
    } catch (err) {
      console.log(`❌ Error: ${err.message}`);
    }
  }

  console.log(`\n✅ Proceso completado - Sensores Precisos`);
  console.log(`Total procesado: ${precisionSensorArticles.length} articulos`);
}

loadSensorArticles();
